Fix compilation with DEBUG=1
Fix missing include:
nxengine/common/StringList.cpp: In member function ‘void StringList::DumpContents()’:
nxengine/common/StringList.cpp:142:2: error: ‘NX_LOG’ was not declared

Fix undeclared reference (replace stat by NX_LOG):
nxengine/ai/sym/sym.o: In function `ai_hvtrigger(Object*)':
nx/nxengine/ai/sym/sym.cpp:150: undefined reference to `stat(char const*, ...)'
nxengine/ai/sym/sym.o: In function `onspawn_spike_small(Object*)':
nx/nxengine/ai/sym/sym.cpp:1189: undefined reference to `stat(char const*, ...)'
nxengine/object.o: In function `Object::SetType(int)':
nx/nxengine/object.cpp:105: undefined reference to `stat(char const*, ...)'